export enum PaymentMethod {
  DINHEIRO = 'DINHEIRO',
  PIX = 'PIX',
  CARTAO_CREDITO = 'CARTAO_CREDITO',
  CARTAO_DEBITO = 'CARTAO_DEBITO',
  FIADO = 'FIADO',
  PAGAMENTO_ONLINE = 'PAGAMENTO_ONLINE',
}
